FROM node:20-alpine

WORKDIR /app

RUN apk add --no-cache \
    vips-dev \
    python3 \
    make \
    g++

COPY package*.json ./
RUN npm install

RUN mkdir -p /app/output

COPY . .

EXPOSE 8000

CMD ["npm", "run", "start:dev"]

